apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80   # Exposing port 80 for HTTP traffic
      targetPort: 80  # The port your React app listens on
  type: LoadBalancer  # Expose the service publicly via a load balancer
