apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1  # You can scale later if needed
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: kartikeyypandeyy/frontend-calculator:latest
 # Use the name of your frontend image
          ports:
            - containerPort: 5000
